spring.application.name=hibernate-advanced-demo
spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8081

#Reduce logging level. Only warn is displayed
logging.level.root=WARN

# Turn off Spring Boot Banner
spring.main.banner-mode=off

# Add logging configs to display SQL statements
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Configure JPA/Hibernate to auto create the tables
spring.jpa.hibernate.ddl-auto=update
